version: '3.8'

services:
  nginx-proxy:
    build: ./nginx  # Ensure this directory contains a Dockerfile
    restart: always
    volumes:
      - ./nginx/default.conf:/tmp/default.conf
    environment: 
      - FLASK_SERVER_ADDR=flask-app:8000
    ports:
      - "8001:8001"
    depends_on:
      - flask-app
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:80/health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: /app/start.sh
    networks:
      - my_overlay_network

  flask-app:
    build: ./server  # Ensure this directory contains a Dockerfile
    restart: always
    ports: 
      - '8000:8000'
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8000/flask-health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: gunicorn -w 3 -t 60 -b 0.0.0.0:8000 app:app
    networks:
      - my_overlay_network

  hello-world:
    build: ./hello-world  # Ensure this directory contains a Dockerfile
    image: josedallatorre/hello-world:latest
    restart: always
    networks:
      - my_overlay_network
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:5000 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    deploy:
      placement:
        constraints: [node.role == worker]

networks:
  my_overlay_network:
    driver: overlay

