  - name: ssh proxy command
    uses: appleboy/ssh-action@v1.0.3
    with:
      host: ${{ secrets.HOST }}
      username: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASSWORD }}
      port: ${{ secrets.PORT }}
      script: |
        mkdir abc/def
        ls -al
